routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Public rute -----------------------------------

Route::get('/blog', 'AdministrationController@blog');

Route::get('/blog/{id}', 'AdministrationController@blogDetail');



// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/blog', 'BlogController');

Route::resource('admin/tournaments', 'TournamentController');

Route::resource('admin/reservations', 'ReservationController');

Route::post('/reserve', 'WebsiteController@reserveDevices')->name('website.reservation');

Route::post('/device-status-change/{id}', 'PcSonyController@toggleStatus');

Route::get('/report', 'PCSonyController@reportShow');

Route::get('/report-reset', 'PCSonyController@reportReset');

Route::get('/report-download', 'PCSonyController@reportDownload');


Route::get('/check', 'ReservationController@checkReservation');

Route::get('/reservations-delete', 'ReservationController@delete');

app/Tournaments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tournaments extends Model
{
    protected $fillable = [
        'name',
        'cost',
        'price',
        'photo',
        'description'
    ];

    public function teamTournament() {
        return $this->belongsTo(TeamTournament::class);
    }
}

app/Http/Controllers/TournamentController.php
<?php

namespace App\Http\Controllers;

use App\Tournaments;
use Illuminate\Http\Request;

class TournamentController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index() {

        $tournaments = Tournaments::all();
        return view('admin.tournament.index', compact('tournaments'));

    }

    public function create() {
        return view('admin.tournament.create');
    }

    public function store(Request $request) {

        $data = $request->validate([
            'name' => 'required|min:3',
            'cost' => 'required',
            'price' => 'required',
            'text' => 'required|min:20',
            'photo' => 'required'
        ]);

        $extension = $data['photo']->getClientOriginalExtension();
        $filename = str_random(10) . '.' . $extension;
        $data['photo']->move(public_path() . '/images/', $filename);

        Tournaments::create([
            'name' => $data['name'],
            'cost' => $data['cost'],
            'price' => $data['price'],
            'description' => $data['text'],
            'photo' => '/images/' . $filename
        ]);

        return redirect(route('tournaments.index'));
    }

    public function destroy($id) {

        Tournaments::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/tournament/create.blade.php
@extends('layouts.panel')

@section('content')


<!-- Sidebar Navigation end-->
<div class="page-content">
  <!-- Page Header-->

  <section class="no-padding-top">
    <div class="container-fluid">
      <div class="row">
        <!-- Form Elements -->
        <div class="col-lg-12">
          <div class="block">
            <div class="title"><strong>Dodaj Turnir</strong></div>
            <div class="block-body">
              <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="{{route('tournaments.store')}}">
                  @csrf
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Naslov Turnira</label>
                  <div class="col-sm-9">
                    <input type="text" name="name" class="form-control">
                  </div>
                </div>
                <div class="line"></div>
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Naslovna Slika</label>
                  <div class="col-sm-9">
                    <input type="file" name="photo" class="form-control">
                  </div>
                </div>
                <div class="line"></div>
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Opis Turnira</label>
                  <div class="col-sm-9">
                    <textarea type="text" name="text" class="form-control"></textarea>
                  </div>
                </div>
                  <div class="line"></div>
                  <div class="form-group row">
                      <label class="col-sm-3 form-control-label">Ulog po igra&ccaron;u / timu</label>
                      <div class="col-sm-9">
                          <input type="text" name="cost" class="form-control">
                      </div>
                  </div>
                  <div class="line"></div>
                  <div class="form-group row">
                      <label class="col-sm-3 form-control-label">Nagrada po igra&ccaron;u / timu</label>
                      <div class="col-sm-9">
                          <input type="text" name="price" class="form-control">
                      </div>
                  </div>
                <div class="line"></div>
                <div class="form-group row">
                  <div class="col-sm-9 ml-auto">
                   
                    <button type="submit" class="btn btn-primary">Sačuvaj</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  @stop

resources/views/admin/tournament/index.blade.php
@extends('layouts.panel')

@section('content')


<div class="page-content" style="width: 100%;">
  <!-- Page Header-->
  
  <section class="no-padding-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="block">
            <div class="title"><strong>Turniri</strong></div>
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Naslov</th>
                    <th>Slika</th>
                    <th>Opis</th>
                    <th>Ulog</th>
                    <th>Nagrada</th>
                    <th>Link</th>
                    <th>Izbri&scaron;i</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($tournaments as $tournament)
                      <tr>
                          <td>{{$tournament->id}}</td>
                          <td>{{$tournament->name}}</td>
                          <td><img src="{{asset($tournament->photo)}}" width="100"></td>
                          <td>{{$tournament->description}}</td>
                          <td>{{$tournament->cost}}</td>
                          <td>{{$tournament->price}}</td>
                          <td><a href="/tournament/{{$tournament->id}}" class="btn btn-sm btn-primary">Link</a></td>
                          <td>
                              <form action="{{route('tournaments.destroy', $tournament->id)}}" method="POST">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" name="submit" class="btn btn-danger btn-sm">Izbri&scaron;i</button>
                              </form>
                          </td>

                      </tr>
                  @endforeach
                 
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  @stop