routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Public rute -----------------------------------

Route::get('/blog', 'AdministrationController@blog');

Route::get('/blog/{id}', 'AdministrationController@blogDetail');



// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/blog', 'BlogController');

Route::resource('admin/tournaments', 'TournamentController');

Route::resource('admin/reservations', 'ReservationController');

Route::post('/reserve', 'WebsiteController@reserveDevices')->name('website.reservation');

Route::post('/device-status-change/{id}', 'PcSonyController@toggleStatus');

Route::get('/report', 'PCSonyController@reportShow');

Route::get('/report-reset', 'PCSonyController@reportReset');

Route::get('/report-download', 'PCSonyController@reportDownload');


Route::get('/check', 'ReservationController@checkReservation');

Route::get('/reservations-delete', 'ReservationController@delete');

app/Reservation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reservation extends Model
{
    protected $fillable = [
        'name',
        'type',
        'num',
        'time',
        'phone',
        'status'
    ];
}

app/Http/Controllers/ReservationController.php
<?php

namespace App\Http\Controllers;

use App\Reservation;
use Illuminate\Http\Request;

class ReservationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index() {

        $reservations = Reservation::latest()->get();
        return view('admin.reservation.index', compact('reservations'));
    }

    public function update(Request $request, $id) {

        $reservation = Reservation::find($id);

        if($request->status == 'Prihvati') {

            $reservation->update(['status' => 'Potvrdjen']);
        }
        if($request->status == 'Odbij') {

            $reservation->update(['status' => 'Odbijen']);
        }

        return redirect()->back();
    }


    public function checkReservation()
    {

        $reservations = Reservation::where('status', 'Cekanje')->get();

        if ($reservations && sizeof($reservations) > 0) {
            return 'true';
        } else {
            return 'false';
        }
    }
    public function delete(){
        Reservation::truncate();
        return redirect()->back();

    }
}

resources/views/admin/reservation/index.blade.php
@extends('layouts.panel')

@section('content')


    <div class="page-content" style="width: 100%;">
        <!-- Page Header-->

        <section class="no-padding-top">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="block">
                            <div class="title"><strong>Rezervacije</strong></div>
                            <div class="pull-right">
                                <a href="/reservations-delete" class="btn btn-danger btn-sm">Resetuj</a>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Ime</th>
                                        <th>PC / PS4</th>
                                        <th>Broj PC / PS4</th>
                                        <th>Vrijeme Rezervacije</th>
                                        <th>Broj telefona</th>
                                        <th>Vrijeme zahtjeva</th>
                                        <th>Status</th>
                                        <th>Potvrdi</th>
                                        <th>Odbij</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($reservations as $reservation)
                                        <tr>
                                            <td>{{$reservation->id}}</td>
                                            <td>{{$reservation->name}}</td>
                                            <td>{{$reservation->type}}</td>
                                            <td>{{$reservation->num}}</td>
                                            <td>{{$reservation->time}}</td>
                                            <td>{{$reservation->phone}}</td>
                                            <td>{{$reservation->created_at}}</td>
                                            <td><span @if($reservation->status == 'Cekanje') style="color: orange" @elseif($reservation->status == 'Potvrdjen') style="color:forestgreen" @else style="color:red" @endif">{{$reservation->status}}</span></td>
                                            <td>
                                                @if($reservation->status == 'Cekanje' || $reservation->status == 'Odbijen')
                                                    <form action="{{route('reservations.update', $reservation->id)}}" method="POST">
                                                        @csrf
                                                        @method('PATCH')
                                                        <input type="hidden" value="Prihvati" name="status">
                                                <button class="btn btn-success btn-sm" type="submit">Prihvati</button>
                                                    </form>
                                                    @endif
                                            </td>
                                            <td>
                                                @if($reservation->status == 'Cekanje' || $reservation->status == 'Potvrdjen')
                                                    <form action="{{route('reservations.update', $reservation->id)}}" method="POST">
                                                        @csrf
                                                        @method('PATCH')
                                                        <input type="hidden" value="Odbij" name="status">
                                                        <button class="btn btn-danger btn-sm" type="submit">Odbij</button>
                                                    </form>
                                                    @endif
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop