routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Public rute -----------------------------------

Route::get('/blog', 'AdministrationController@blog');

Route::get('/blog/{id}', 'AdministrationController@blogDetail');



// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/blog', 'BlogController');

Route::resource('admin/tournaments', 'TournamentController');

Route::resource('admin/reservations', 'ReservationController');

Route::post('/reserve', 'WebsiteController@reserveDevices')->name('website.reservation');

Route::post('/device-status-change/{id}', 'PcSonyController@toggleStatus');

Route::get('/report', 'PCSonyController@reportShow');

Route::get('/report-reset', 'PCSonyController@reportReset');

Route::get('/report-download', 'PCSonyController@reportDownload');


Route::get('/check', 'ReservationController@checkReservation');

Route::get('/reservations-delete', 'ReservationController@delete');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = [
        'name',
        'photo',
        'body'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;
use App\Exception;

class BlogController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $blogs = Blog::all();
        return view('admin.blog.index', compact('blogs'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.blog.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

        $data = $request->validate([
           'name' => 'required|min:3',
           'photo' => 'required',
           'body' => 'required|min:50'
        ]);

        $extension = $data['photo']->getClientOriginalExtension();
        $filename = str_random(10) . '.' . $extension;
        $data['photo']->move(public_path() . '/images/', $filename);

        Blog::create([
           'name' => $data['name'],
           'photo' => '/images/' . $filename,
           'body' => $data['body']
        ]);



        return redirect()->back()->with('success', 'Uspjesno');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::find($id);
        return view('admin.blog.show', compact('blog'));

        // TODO napraviti admin.blog.show stranicu
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Blog::find($id)->delete();
        return redirect()->back()->with('success', 'Uspjesno');
    }
}

resources/views/admin/blog/create.blade.php
@extends('layouts.panel')

@section('content')


<!-- Sidebar Navigation end-->
<div class="page-content">


  <section class="no-padding-top">
    <div class="container-fluid">
      <div class="row">
        <!-- Form Elements -->
        <div class="col-lg-12">
          <div class="block">
            <div class="title"><strong>Dodaj Blog</strong></div>
            <div class="block-body">
              <form class="form-horizontal" method="POST" action="{{route('blog.store')}}" enctype="multipart/form-data">
                  @csrf
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Naslov:</label>
                  <div class="col-sm-9">
                    <input type="string" name="name" class="form-control">
                  </div>
                </div>
                <div class="line"></div>
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Naslovna Slika:</label>
                  <div class="col-sm-9">
                    <input type="file" name="photo" class="form-control">
                  </div>
                </div>
                <div class="line"></div>
                <div class="form-group row">
                  <label class="col-sm-3 form-control-label">Tekst Bloga:</label>
                  <div class="col-sm-9">
                    <textarea type="text" name="body" class="form-control"></textarea>
                  </div>
                </div>
                <div class="line"></div>
                <div class="form-group row">
                  <div class="col-sm-9 ml-auto">
                    <button type="submit" class="btn btn-primary">Sačuvaj</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@stop

resources/views/admin/blog/index.blade.php
@extends('layouts.panel')

@section('content')


<!-- Sidebar Navigation end-->
<div class="page-content" style="width: 100%;">
  <!-- Page Header-->
 
  <!-- Breadcrumb-->

  <section class="no-padding-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="block">
            <div class="title"><strong>Blogovi</strong></div>
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                  <tr class="text-center">
                    <th>#</th>
                    <th>Naslov</th>
                    <th>Slika</th>
                    <th>Tekst</th>
                    <th>Link</th>
                    <th>Izbri&scaron;i</th>
                  </tr>
                </thead>
                <tbody>
                @foreach($blogs as $blog)
                  <tr class="text-center">
                    <td>{{$blog->id}}</td>
                      <td>{{$blog->name}}</td> 
                      <td><img src="{{asset($blog->photo)}}" width="100"></td>
                      <td>{{str_limit($blog->body,50)}}</td>
                    <td><a href="/blog/{{$blog->id}}" target="_blank" class="btn btn-info btn-sm">Link</a></td>
                    <td>
                        <form action="{{route('blog.destroy', $blog->id)}}" method="POST">
                            @method('DELETE')
                            @csrf
                      <button class="btn btn-danger btn-sm" type="submit">Izbri&scaron;i</button>
                        </form>
                    </td>
                  </tr>
                @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  @stop